name: aria-recsys
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - faiss-cpu=1.7.4
  - libblas=*=*openblas
  - pytorch=2.2
  - cpuonly
  - pip
  - pip:
      - streamlit==1.36.0
      - sentence-transformers==3.0.1
      - transformers==4.41.2
      - safetensors==0.4.3
      - google-generativeai==0.7.2
