# name: aria-recsys
# channels:
#   - conda-forge
#   - pytorch
# dependencies:
#   - python=3.10
#   - numpy
#   - pandas
#   - scikit-learn
#   - faiss-cpu=1.7.4
#   - libblas=*=*openblas
#   - pytorch=2.2
#   - cpuonly
#   - pip
#   - pip:
#       - streamlit==1.36.0
#       - sentence-transformers==3.0.1
#       - transformers==4.41.2
#       - safetensors==0.4.3
#       - google-generativeai==0.7.2

name: aria-recsys
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.48.0
      - sentence-transformers==3.0.1
      - torch==2.2.2
      - transformers==4.43.3
      - scikit-learn==1.5.0
      - pandas==2.1.0
      - numpy==1.24.0
      - google-generativeai==0.8.5